# file: roles/install-pgbouncer/tasks/install.yml

- name: "Stage 0: install repository package"
  yum:
    state: present
    pkg: "{{ item.repo }}"
  when: item.version == "{{ postgresql_version }}"
  with_items: "{{ vars ['psql_repo_' + ansible_distribution] }}"

- name: "Stage 1: install pgbouncer"
  yum: pkg=pgbouncer state=latest
  when: ansible_pkg_mgr == 'yum'
